### PR TITLE
Fix empty reason displayed --fixes #38

### LINKED ISSUE #38: NULL is displayed when no reason is provided
It seems that if no reason for granting coins is provided, `null` string is displayed:

`You have been granted 1 new, shiny :coin: null. You now have...`

### PR DESCRIPTION
**Pull request by karolsojko**
Fix empty reason displayed --fixes #38

### CODE REVIEW

File: src/services/slack.js [hunk 1]
```diff
@@ -1,12 +1,12 @@
...
 
-const notifyUserAboutCoinGranted = (userName, totalCoins, reason) => {
+const notifyUserAboutCoinGranted = (userName, totalCoins, reason = 'no reason') => {
   const slackClient = new Slack(process.env.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN);
 
   return new Promise((resolve, reject) => {
     slackClient.api('chat.postMessage', {
       channel: `@${userName}`,
-      text: `You have been granted 1 new, shiny :coin: ${reason}. You now have ${totalCoins} :coin:. Redeem them at: https://x-team.com/vault`
+      text: `You have been granted 1 new, shiny :coin: for "${reason}". You now have ${totalCoins} :coin:. Redeem them at: https://x-team.com/vault`
```
Comment (jacekelgda) [inline src/services/slack.js]: Do we really want to say it this way? `You have been granted 1 coin for no reason`? Maybe this will be confusing? What about `Reason was not provided`?

Comment (karolsojko) [reply src/services/slack.js]: Fixed
